package com.moltenwolfcub.crafted_cuisine.datagen.loot;

import java.util.function.BiConsumer;

import com.moltenwolfcub.crafted_cuisine.CraftedCuisine;
import com.moltenwolfcub.crafted_cuisine.init.ModBlockItems;
import com.moltenwolfcub.crafted_cuisine.init.ModItems;

import net.minecraft.data.loot.ChestLoot;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.alchemy.Potions;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.LootTable.Builder;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.EnchantRandomlyFunction;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.functions.SetPotionFunction;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator;

public class ModChestLootTables extends ChestLoot {

    private static final ResourceLocation BARK_CHEST = new ResourceLocation(CraftedCuisine.MODID, "chests/bark_chest");

    //blackstone_fortress
    private static final ResourceLocation DEFAULT_CHEST = new ResourceLocation(CraftedCuisine.MODID, "chests/blackstone_fortress_basic");
    private static final ResourceLocation ARMORY_CHEST = new ResourceLocation(CraftedCuisine.MODID, "chests/blackstone_fortress_armory");
    private static final ResourceLocation LAVA_CHEST = new ResourceLocation(CraftedCuisine.MODID, "chests/blackstone_fortress_lava");
    private static final ResourceLocation THRONE_CHEST = new ResourceLocation(CraftedCuisine.MODID, "chests/blackstone_fortress_throne");
    private static final ResourceLocation TOWER_CHEST = new ResourceLocation(CraftedCuisine.MODID, "chests/blackstone_fortress_tower");

    @Override
    public void accept(BiConsumer<ResourceLocation, Builder> builder) {
        addBlackstoneFortress(builder);

        builder.accept(BARK_CHEST, LootTable.lootTable()
            .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(1.0F, 5.0F))
                .add(LootItem.lootTableItem(ModItems.ACACIA_BARK.get()).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0f, 10.0f))))
                .add(LootItem.lootTableItem(ModItems.BIRCH_BARK.get()).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0f, 10.0f))))
                .add(LootItem.lootTableItem(ModItems.DARK_OAK_BARK.get()).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0f, 10.0f))))
                .add(LootItem.lootTableItem(ModItems.JUNGLE_BARK.get()).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0f, 10.0f))))
                .add(LootItem.lootTableItem(ModItems.OAK_BARK.get()).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0f, 10.0f))))
                .add(LootItem.lootTableItem(ModItems.SPRUCE_BARK.get()).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0f, 10.0f))))
                .add(LootItem.lootTableItem(ModItems.CINNAMON_BARK.get()).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0f, 10.0f))))
            )
        );
    }

    public static void addBlackstoneFortress(BiConsumer<ResourceLocation, Builder> builder) {
        builder.accept(DEFAULT_CHEST, LootTable.lootTable()
            .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(2.0f, 6.0f))
                .add(LootItem.lootTableItem(Items.BLACKSTONE)
                    .setWeight(20)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 20f)))
                )
                .add(LootItem.lootTableItem(ModItems.REINFORCED_BLACKSTONE_NUGGET.get())
                    .setWeight(18)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 18f)))
                )
                .add(LootItem.lootTableItem(ModItems.REINFORCED_BLACKSTONE_NUGGET.get())
                    .setWeight(18)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 18f)))
                )
                .add(LootItem.lootTableItem(ModItems.REINFORCED_BLACKSTONE_INGOT.get())
                    .setWeight(15)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 4f)))
                )
                .add(LootItem.lootTableItem(ModItems.REINFORCED_BLACKSTONE_SWORD.get())
                    .setWeight(13)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                    .apply(EnchantRandomlyFunction.randomApplicableEnchantment())
                )
                .add(LootItem.lootTableItem(Items.IRON_INGOT)
                    .setWeight(10)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 5f)))
                )
                .add(LootItem.lootTableItem(Items.GOLD_INGOT)
                    .setWeight(8)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
                )
                .add(LootItem.lootTableItem(Items.EMERALD)
                    .setWeight(5)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 4f)))
                )
                .add(LootItem.lootTableItem(ModBlockItems.REINFORCED_BLACKSTONE.get())
                    .setWeight(3)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                )
                .add(LootItem.lootTableItem(Items.GILDED_BLACKSTONE)
                    .setWeight(2)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                )
                .add(LootItem.lootTableItem(Items.DIAMOND)
                    .setWeight(1)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                )
            )
        );
        builder.accept(ARMORY_CHEST, LootTable.lootTable()
            .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(3.0f, 5.0f))
                .add(LootItem.lootTableItem(ModItems.REINFORCED_BLACKSTONE_INGOT.get())
                    .setWeight(20)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 10f)))
                )
                .add(LootItem.lootTableItem(ModItems.REINFORCED_BLACKSTONE_SWORD.get())
                    .setWeight(19)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                    .apply(EnchantRandomlyFunction.randomApplicableEnchantment())
                )
                .add(LootItem.lootTableItem(ModItems.REINFORCED_BLACKSTONE_CHESTPLATE.get())
                    .setWeight(18)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                    .apply(EnchantRandomlyFunction.randomApplicableEnchantment())
                )
                .add(LootItem.lootTableItem(ModItems.REINFORCED_BLACKSTONE_AXE.get())
                    .setWeight(17)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                    .apply(EnchantRandomlyFunction.randomApplicableEnchantment())
                )
                .add(LootItem.lootTableItem(ModItems.REINFORCED_BLACKSTONE_NUGGET.get())
                    .setWeight(15)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(3f, 20f)))
                )
                .add(LootItem.lootTableItem(Items.IRON_SWORD)
                    .setWeight(13)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                )
                .add(LootItem.lootTableItem(ModItems.REINFORCED_BLACKSTONE_LEGGINGS.get())
                    .setWeight(13)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                    .apply(EnchantRandomlyFunction.randomApplicableEnchantment())
                )
                .add(LootItem.lootTableItem(Items.GOLDEN_SWORD)
                    .setWeight(13)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                    .apply(EnchantRandomlyFunction.randomApplicableEnchantment())
                )
                .add(LootItem.lootTableItem(ModItems.REINFORCED_BLACKSTONE_HELMET.get())
                    .setWeight(13)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                    .apply(EnchantRandomlyFunction.randomApplicableEnchantment())
                )
                .add(LootItem.lootTableItem(ModItems.REINFORCED_BLACKSTONE_BOOTS.get())
                    .setWeight(11)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                    .apply(EnchantRandomlyFunction.randomApplicableEnchantment())
                )
                .add(LootItem.lootTableItem(Items.IRON_INGOT)
                    .setWeight(8)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 5f)))
                )
                .add(LootItem.lootTableItem(Items.STONE_SWORD)
                    .setWeight(8)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                )
                .add(LootItem.lootTableItem(Items.GOLD_NUGGET)
                    .setWeight(8)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(3f, 10f)))
                )
                .add(LootItem.lootTableItem(Items.BLACKSTONE)
                    .setWeight(5)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(3f, 5f)))
                )
            )
        );
        builder.accept(LAVA_CHEST, LootTable.lootTable()
            .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(2.0f, 4.0f))
                .add(LootItem.lootTableItem(Items.MAGMA_CREAM)
                    .setWeight(10)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 13f)))
                )
                .add(LootItem.lootTableItem(Items.MAGMA_BLOCK)
                    .setWeight(8)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
                )
                .add(LootItem.lootTableItem(Items.FIRE_CHARGE)
                    .setWeight(6)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 5f)))
                )
                .add(LootItem.lootTableItem(Items.LAVA_BUCKET)
                    .setWeight(5)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                )
                .add(LootItem.lootTableItem(Items.POTION)
                    .setWeight(2)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                    .apply(SetPotionFunction.setPotion(Potions.FIRE_RESISTANCE))
                )
                .add(LootItem.lootTableItem(Items.BLAZE_POWDER)
                    .setWeight(1)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                )
            )
        );
        builder.accept(THRONE_CHEST, LootTable.lootTable()
            .withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1))
                .add(LootItem.lootTableItem(Items.NETHERITE_INGOT)
                    .setWeight(49)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                )
                .add(LootItem.lootTableItem(Items.NETHERITE_INGOT)
                    .setWeight(1)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(2)))
                )
            )
            .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(3, 6))
                .add(LootItem.lootTableItem(Items.GOLD_INGOT)
                    .setWeight(100)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 10)))
                )
                .add(LootItem.lootTableItem(Items.EMERALD)
                    .setWeight(95)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                )
                .add(LootItem.lootTableItem(Items.DIAMOND)
                    .setWeight(95)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(2, 9)))
                )
                .add(LootItem.lootTableItem(Items.GOLDEN_APPLE)
                    .setWeight(80)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                )
                .add(LootItem.lootTableItem(Items.DIAMOND_SWORD)
                    .setWeight(80)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                    .apply(EnchantRandomlyFunction.randomApplicableEnchantment())
                )
                .add(LootItem.lootTableItem(Items.IRON_INGOT)
                    .setWeight(70)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(2, 10)))
                )
                .add(LootItem.lootTableItem(Items.ENCHANTED_GOLDEN_APPLE)
                    .setWeight(20)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                )
            )
        );
        builder.accept(TOWER_CHEST, LootTable.lootTable()
            .withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1))
                .add(LootItem.lootTableItem(Items.BOW)
                    .setWeight(9)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                )
                .add(LootItem.lootTableItem(Items.CROSSBOW)
                    .setWeight(10)
                    .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                )
            )
            .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(2, 4))
                .add(LootItem.lootTableItem(Items.ARROW)
                    .setWeight(12)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 10)))
                )
                .add(LootItem.lootTableItem(Items.SPECTRAL_ARROW)
                    .setWeight(10)
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(3, 8)))
                )
                .add(LootItem.lootTableItem(Items.TIPPED_ARROW)
                    .setWeight(6)
                    .apply(SetPotionFunction.setPotion(Potions.WEAKNESS))
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5)))
                )
                .add(LootItem.lootTableItem(Items.TIPPED_ARROW)
                    .setWeight(5)
                    .apply(SetPotionFunction.setPotion(Potions.SLOWNESS))
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 4)))
                )
                .add(LootItem.lootTableItem(Items.TIPPED_ARROW)
                    .setWeight(2)
                    .apply(SetPotionFunction.setPotion(Potions.POISON))
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 3)))
                )
                .add(LootItem.lootTableItem(Items.TIPPED_ARROW)
                    .setWeight(1)
                    .apply(SetPotionFunction.setPotion(Potions.HARMING))
                    .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 2)))
                )
            )
        );
    }
    
}
